### ISSUE TITLE
TypeError: string indices must be integers, not unicode

### ISSUE THREAD

**Issue by chadwhitacre** [gratipay/gratipay.com#1566]
Discovered by @clone1018 while trying to get a tips.json client going:

```
Traceback (most recent call last):
  File "aspen/website.py", line 81, in handle_safely
    response = self.handle(request)
  File "aspen/website.py", line 114, in handle
    response = request.resource.respond(request)
  File "aspen/resources/dynamic_resource.py", line 52, in respond
    exec self.pages[1] in context
  File "/app/www/%username/tips.json.spt", line 19, in <module>
    seen.add(tip['username'])
TypeError: string indices must be integers, not unicode
```

https://app.getsentry.com/gittip/gittip/group/8477799/

**Comment by raheem1316** [comment]
please give a solution to this....

Traceback (most recent call last):
  File "C:\Users\Raheem Shaik\Desktop\practise1.py", line 653, in <module>
    result = client.service.leadmanagementLeadserviceListuserlead(accessToken,role,attributes,conditions,filters,leadLimit,leadIndex,due_amount_filter,isWebReq)
  File "C:\Python27\lib\site-packages\zeep\client.py", line 45, in __call__
    self._op_name, args, kwargs)
  File "C:\Python27\lib\site-packages\zeep\wsdl\bindings\soap.py", line 110, in send
    options=options)
  File "C:\Python27\lib\site-packages\zeep\wsdl\bindings\soap.py", line 68, in _create
    serialized = operation_obj.create(*args, **kwargs)
  File "C:\Python27\lib\site-packages\zeep\wsdl\definitions.py", line 197, in create
    return self.input.serialize(*args, **kwargs)
  File "C:\Python27\lib\site-packages\zeep\wsdl\messages\soap.py", line 64, in serialize
    self.body.render(body, body_value)
  File "C:\Python27\lib\site-packages\zeep\xsd\elements\element.py", line 191, in render
    self._render_value_item(parent, value, render_path)
  File "C:\Python27\lib\site-packages\zeep\xsd\elements\element.py", line 215, in _render_value_item
    return self.type.render(node, value, None, render_path)
  File "C:\Python27\lib\site-packages\zeep\xsd\types\complex.py", line 253, in render
    element.render(parent, element_value, child_path)
  File "C:\Python27\lib\site-packages\zeep\xsd\elements\indicators.py", line 241, in render
    element.render(parent, element_value, child_path)
  File "C:\Python27\lib\site-packages\zeep\xsd\elements\element.py", line 191, in render
    self._render_value_item(parent, value, render_path)
  File "C:\Python27\lib\site-packages\zeep\xsd\elements\element.py", line 215, in _render_value_item
    return self.type.render(node, value, None, render_path)
  File "C:\Python27\lib\site-packages\zeep\xsd\types\complex.py", line 224, in render
    attr_value = value[name] if name in value else NotSet
TypeError: string indices must be integers, not unicode
