### ISSUE TITLE
bug in oauthlib means we see the wrong error

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#2869]
```
Traceback (most recent call last):
  File "site-packages/algorithm.py", line 288, in run
    new_state = function(**deps.as_kwargs)
  File "aspen/algorithms/website.py", line 75, in get_response_for_resource
    return {'response': resource.respond(request)}
  File "aspen/resources/dynamic_resource.py", line 56, in respond
    exec self.pages[1] in context
  File "/app/www/on/%platform/associate.spt", line 29, in <module>
    sess = platform.handle_auth_callback(url, query_id, query_data)
  File "gratipay/elsewhere/__init__.py", line 273, in handle_auth_callback
    authorization_response=url)
  File "requests_oauthlib/oauth2_session.py", line 160, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "oauthlib/oauth2/rfc6749/clients/base.py", line 409, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "oauthlib/oauth2/rfc6749/parameters.py", line 376, in parse_token_response
    validate_token_parameters(params)
  File "oauthlib/oauth2/rfc6749/parameters.py", line 386, in validate_token_parameters
    raise MissingTokenError(description="Missing access token parameter.")
MissingTokenError: (missing_token) Missing access token parameter.
```

https://app.getsentry.com/gratipay/gratipay-com/group/37832004/
##

**Comment by nobodxbodon** [comment]
No action item for us? Please reopen if I'm wrong.
