### ISSUE TITLE
another bug in oauthlib error handling

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#2870]
cf. #2869

```
Traceback (most recent call last):
  File "site-packages/algorithm.py", line 288, in run
    new_state = function(**deps.as_kwargs)
  File "aspen/algorithms/website.py", line 75, in get_response_for_resource
    return {'response': resource.respond(request)}
  File "aspen/resources/dynamic_resource.py", line 56, in respond
    exec self.pages[1] in context
  File "/app/www/on/%platform/associate.spt", line 29, in <module>
    sess = platform.handle_auth_callback(url, query_id, query_data)
  File "gratipay/elsewhere/__init__.py", line 273, in handle_auth_callback
    authorization_response=url)
  File "requests_oauthlib/oauth2_session.py", line 134, in fetch_token
    state=self._state)
  File "oauthlib/oauth2/rfc6749/clients/web_application.py", line 173, in parse_request_uri_response
    response = parse_authorization_code_response(uri, state=state)
  File "oauthlib/oauth2/rfc6749/parameters.py", line 168, in parse_authorization_code_response
    raise MissingCodeError("Missing code parameter in response.")
MissingCodeError: (missing_code) Missing code parameter in response.
```

https://app.getsentry.com/gratipay/gratipay-com/group/31426686/
##

**Comment by nobodxbodon** [comment]
Closing as no action item here. Please reopen if otherwise.
