### ISSUE TITLE
jstests fail in Vagrant/VirtualBox

### ISSUE THREAD

**Issue by techtonik** [gratipay/gratipay.com#3000]
Seems like I forgot some `jstest` dependency, but can't figure out which exactly. Travis works ok and that's strange.

```
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ make jstest
node_modules/grunt-cli/bin/grunt test
Running "jshint:gruntfile" (jshint) task
>> 1 file lint free.

Running "jshint:js" (jshint) task
>> 16 files lint free.

Running "jshint:tests" (jshint) task
>> 5 files lint free.

Running "aspen:start" task
Starting Aspen... started.

Running "webdriver:tests" (webdriver) task

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)
make: *** [jstest] Error 8
```

Any ideas what can go wrong? @rummik

**Comment by rummik** [comment]
@techtonik I think this is related to the helper script to let JS tests get a session

**Comment by techtonik** [comment]
@rummik, I am experiencing trouble locating the entrypoint to unwind this problem. Can you point where is the script exactly and how I can execute/debug it manually without Grunt?

**Comment by rummik** [comment]
@techtonik [tests/js/utils/](https://github.com/gratipay/gratipay.com/tree/a02471f4e9573840a730ae0af73c5f9526405d05/tests/js/utils/)

**Comment by techtonik** [comment]
I don't get where should I "require" that session?

```
vagrant@vagrant-ubuntu-trusty-64:/vagrant/tests/js/utils$ node
> var createSession = require('session.js');
Error: Cannot find module 'session.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at repl:1:21
    at REPLServer.self.eval (repl.js:110:21)
    at repl.js:249:20
    at REPLServer.self.eval (repl.js:122:7)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.EventEmitter.emit (events.js:95:17)
```

**Comment by techtonik** [comment]
Trying to get some debug info:
```
$ node_modules/grunt-cli/bin/grunt -d -v test
...
Starting Aspen... started.

Running "webdriver" task
[D] Task source: /vagrant/node_modules/grunt-webdriver/tasks/webdriver.js

Running "webdriver:tests" (webdriver) task
[D] Task source: /vagrant/node_modules/grunt-webdriver/tasks/webdriver.js
Verifying property webdriver.tests exists in config...OK
File: [no files]
Options: reporter="spec", ui="bdd", slow=75, bail=false, grep=null, timeout=1000000, updateSauceJob=false, output=null, quiet=false, no
spawn=false, desiredCapabilities={"browserName":"phantomjs"}
[D] run webdriverio with following capabilities: {"reporter":"spec","ui":"bdd","slow":75,"bail":false,"grep":null,"timeout":1000000,"up
dateSauceJob":false,"output":null,"quiet":false,"nospawn":false,"desiredCapabilities":{"browserName":"phantomjs"}}
[D] start selenium standalone server

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)
```

Looks like it is unable to start selenium.

**Comment by techtonik** [comment]
Tracked this down to bug in https://github.com/vvo/node-whereis/issues/4

It appeared that I don't have Java installed, which was not an issue for Travis http://docs.travis-ci.com/user/languages/java/

**Comment by techtonik** [comment]
Now I am getting the same error as in #3069

**Comment by techtonik** [comment]
After webdriverio/grunt-webdriver/pull/58 is merged, the error message will be
```
.../node_modules/selenium-standalone/node_modules/which/which.js:136
  throw new Error('not found: '+cmd)
        ^
Error: not found: java
    at Function.whichSync [as sync] (/root/gpgit/node_modules/grunt-webdriver/node_modules/selenium-standalone/node_modules/which/which.js:136:9)
    at Object.start (/root/gpgit/node_modules/grunt-webdriver/node_modules/selenium-standalone/lib/start.js:45:27)
    at async.waterfall.callback (/root/gpgit/node_modules/grunt-webdriver/tasks/webdriver.js:234:39)
    at fn (/root/gpgit/node_modules/grunt-webdriver/node_modules/async/lib/async.js:638:34)
    at Object._onImmediate (/root/gpgit/node_modules/grunt-webdriver/node_modules/async/lib/async.js:554:34)
    at processImmediate [as _immediateCallback] (timers.js:330:15)
make: *** [jstest] Error 8
```
Which is more obvious reason that Java is not installed.

**Comment by techtonik** [comment]
The rest of the problems are in #3069.
