### ISSUE TITLE
don't 500 when Twitter does

### ISSUE THREAD

**Issue by colindean** [gratipay/gratipay.com#3062]
```
Internal Server Error, program!
Traceback (most recent call last):
  File "/Users/colin/Source/gratipay/gratipay.com/env/lib/python2.7/site-packages/algorithm.py", line 288, in run
    new_state = function(**deps.as_kwargs)
  File "/Users/colin/Source/gratipay/gratipay.com/env/lib/python2.7/site-packages/aspen/algorithms/website.py", line 100, in get_response_for_resource
    return {'response': resource.respond(request, dispatch_result)}
  File "/Users/colin/Source/gratipay/gratipay.com/env/lib/python2.7/site-packages/aspen/resources/simplate.py", line 56, in respond
    exec self.pages[1] in context
  File "/Users/colin/Source/gratipay/gratipay.com/www/on/%platform/associate.spt", line 32, in <module>
    sess = platform.handle_auth_callback(url, query_id, query_data)
  File "/Users/colin/Source/gratipay/gratipay.com/gratipay/elsewhere/__init__.py", line 253, in handle_auth_callback
    r = sess.fetch_access_token(self.auth_url+self.access_token_path)
  File "/Users/colin/Source/gratipay/gratipay.com/env/lib/python2.7/site-packages/requests_oauthlib/oauth1_session.py", line 228, in fetch_access_token
    token = self._fetch_token(url)
  File "/Users/colin/Source/gratipay/gratipay.com/env/lib/python2.7/site-packages/requests_oauthlib/oauth1_session.py", line 264, in _fetch_token
    token = dict(urldecode(self.post(url).text))
  File "/Users/colin/Source/gratipay/gratipay.com/env/lib/python2.7/site-packages/oauthlib/common.py", line 129, in urldecode
    raise ValueError(error % (set(query) - urlencoded, query))
ValueError: Error trying to decode a non urlencoded string. Found invalid characters: set([u'\u7b80', u'\xea', u'\u6587', u'\u043a', u'\n', u'/', u'\u0e17', u'\u05b4', u'\u0e44', u'!', u' ', u'#', u'\u0e22', u"'", u'\u0926', u'\u0629', u'\u0628', u'\u4e2d', u'\u672c', u'\u062f', u'\u0631', u'\u05b0', u'\u0e32', u'\uc5b4', u'\u0648', u'\u0639', u'\u0438', u':', u'<', u'\u8a9e', u'>', u'\u0441', u'\u0940', u'\u0443', u'\u0644', u'\u0420', u'\u0439', u'\u064a', u'\u094d', u'\u05d1', u'\u0939', u'\u4f53', u'"', u'\u0e20', u'\u05d9', u'\ud55c', u'\u05e2', u'\u65e5', u'\u0627', u'\xe7', u'\u05e8', u'\u05ea', u'\uad6d', u'\xf1', u'\u0e29', u'\u093f', u'\u0928', u'\xfc']) in the string: '<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="Content-Language" content="en-us">
    <meta name="robots" content="noindex, nofollow">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Twitter / Error</title>
    <link href="https://abs.twimg.com/favicons/favicon.ico" rel="shortcut icon" type="image/x-icon">
    <link rel="stylesheet" href="https://abs.twimg.com/errors/fullscreen_errors-91ecc652e4fafac52ce8a1a8a181ad24.css">
  </head>
  <body>
    <div class="topbar js-topbar">
      <div class="global-nav" data-section-term="top_nav">
        <div class="global-nav-inner">
          <div class="container">
            <ul class="nav js-global-actions">
              <li class="home">
                <a class="nav-logo-link" href="https://twitter.com"><img class="bird" src="https://abs.twimg.com/errors/logo23x19.png" alt="Twitter"></a>
              </li>
            </ul>
            <div class="pull-right">
              <ul class="nav secondary-nav">
                <li><a href="https://twitter.com" id="homeLink">Home &rarr;</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="blue-sky">
      <div class="body-content">

          <div class="canvas">
            <img class= "illustration robot" src= "https://abs.twimg.com/errors/robot.png" >
          </div>
          <h1>Something is technically wrong.</h1>
          <p>Thanks for noticing&mdash;we're going to fix it up and have things back to normal soon.</p>

        <div class="footer">

            <ul class="languages">

                <li><a data-language="ar" href="#">\u0627\u0644\u0639\u0631\u0628\u064a\u0629</a></li>

                <li><a data-language="da" href="#">Dansk</a></li>

                <li><a data-language="de" href="#">Deutsch</a></li>

                <li><a data-language="en" href="#">English</a></li>

                <li><a data-language="en-gb" href="#">EnglishUK</a></li>

                <li><a data-language="es" href="#">Espa\xf1ol</a></li>

                <li><a data-language="fi" href="#">Suomi</a></li>

                <li><a data-language="fil" href="#">Filipino</a></li>

                <li><a data-language="fr" href="#">fran\xe7ais</a></li>

                <li><a data-language="he" href="#">\u05e2\u05b4\u05d1\u05b0\u05e8\u05b4\u05d9\u05ea</a></li>

                <li><a data-language="hi" href="#">\u0939\u093f\u0928\u094d\u0926\u0940</a></li>

                <li><a data-language="id" href="#">Bahasa Indonesia</a></li>

                <li><a data-language="it" href="#">Italiano</a></li>

                <li><a data-language="ja" href="#">\u65e5\u672c\u8a9e</a></li>

                <li><a data-language="ko" href="#">\ud55c\uad6d\uc5b4</a></li>

                <li><a data-language="nl" href="#">Nederlands</a></li>

                <li><a data-language="no" href="#">Norsk</a></li>

                <li><a data-language="pl" href="#">Polski</a></li>

                <li><a data-language="pt" href="#">Portugu\xeas</a></li>

                <li><a data-language="ru" href="#">\u0420\u0443\u0441\u0441\u043a\u0438\u0439</a></li>

                <li><a data-language="sv" href="#">Svenska</a></li>

                <li><a data-language="th" href="#">\u0e20\u0e32\u0e29\u0e32\u0e44\u0e17\u0e22</a></li>

                <li><a data-language="tr" href="#">T\xfcrk\xe7e</a></li>

                <li><a data-language="ur" href="#">\u0627\u0631\u062f\u0648</a></li>

                <li><a data-language="zh-cn" href="#">\u7b80\u4f53\u4e2d\u6587</a></li>

            </ul>

          <ul class="links">
            <li class="first">&copy; <span id="copyright-year"></span> Twitter</li>
            <li><a href="https://about.twitter.com/">About</a></li>
            <li><a href="https://support.twitter.com/">Help</a></li>
            <li><a href="http://status.twitter.com/">Status</a></li>
          </ul>
        </div>
      </div>
    </div>
    <script src="https://abs.twimg.com/errors/500-06a2aa03f58da16392434844237cb277.js"></script>
  </body>
</html>
'. Please ensure the request/response body is x-www-form-urlencoded.
```

**Comment by clone1018** [comment]
Just ran into this on production and then on my next request I got an internal server error from Twitter. I think twitter is having an issue at the moment.

**Comment by colindean** [comment]
Our error probably shouldn't be so breaky, and provide a user with an escape route.

**Comment by whit537** [comment]
@colindean Mind reticketing that? Got a report from a user as well:

https://twitter.com/yando/status/552292911757684738

**Comment by whit537** [comment]
Actually, let's just use this ticket for that.

!m @colindean

**Comment by Changaco** [comment]
This can't be fixed properly on our side, `requests_oauthlib` needs to be modified to raise a custom exception instead of a generic `ValueError`, so we can catch it and return a 502 containing the error page from Twitter. Tagging as blocked.

**Comment by Changaco** [comment]
Actually, it looks like `requests_oauthlib` has already fixed that issue, so what we need to do is upgrade it.
