### ISSUE TITLE
jstests fail on LXC/LXD setup

### ISSUE THREAD

**Issue by techtonik** [gratipay/gratipay.com#3493]
On a fresh Ubuntu LXD bootstrapped machine, jstest fail partially with the following error. I don't know how to debug this deeper yet.

```
...
Running "aspen:start" task
Aspen seems to be running already. Doing nothing.

Running "webdriver:tests" (webdriver) task


  authed homepage
    1) should render copy correctly

  global helpers
    2) should mock console if it is not supported by the browser

  Gratipay.trim()
    3) should strip all unicode
    4) should strip non-printable ASCII
    5) should trim leading and trailing whitespace


  0 passing (5s)
  5 failing

  1) authed homepage should render copy correctly:
     Uncaught AssertionError: "undefined" == "alice"
      at WebdriverIO.<anonymous> (tests/js/test_authed_homepage.js:26:24)

  2) global helpers should mock console if it is not supported by the browser:
     Uncaught TypeError: Cannot read property 'value' of null
      at WebdriverIO.<anonymous> (tests/js/test_global_helpers.js:18:35)

  3) Gratipay.trim() should strip all unicode:
     Uncaught TypeError: Cannot read property 'value' of null
      at WebdriverIO.<anonymous> (tests/js/test_trim.js:16:37)

  4) Gratipay.trim() should strip non-printable ASCII:
     Uncaught TypeError: Cannot read property 'value' of null
      at WebdriverIO.<anonymous> (tests/js/test_trim.js:33:37)

  5) Gratipay.trim() should trim leading and trailing whitespace:
     Uncaught TypeError: Cannot read property 'value' of null
      at WebdriverIO.<anonymous> (tests/js/test_trim.js:51:37)



Warning: Task "webdriver:tests" failed. Use --force to continue.

Aborted due to warnings.
make: *** [jstest] Error 3
```
##

**Comment by nobodxbodon** [comment]
Guess related with environment. Indeed hard to debug. Mark as obsolete.

**Comment by techtonik** [comment]
I will try again someday. LXD much progressed in 2 years.
