### ISSUE TITLE
Can't build on os x

### ISSUE THREAD

**Issue by aandis** [gratipay/gratipay.com#4095]
New to os x. Not sure if it's something wrong with my setup or `Makefile` itself.

`make env =>`

```bash
"/usr/bin/python2.7" "./vendor/virtualenv-12.0.7.py" \
				--prompt="[gratipay] " \
				--extra-search-dir=./vendor/ \
				--always-copy \
				./env/
Traceback (most recent call last):
  File "./vendor/virtualenv-12.0.7.py", line 2352, in <module>
    main()
  File "./vendor/virtualenv-12.0.7.py", line 825, in main
    symlink=options.symlink)
  File "./vendor/virtualenv-12.0.7.py", line 985, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "./vendor/virtualenv-12.0.7.py", line 1179, in install_python
    copyfile(join(stdlib_dir, fn), join(lib_dir, fn), symlink)
  File "./vendor/virtualenv-12.0.7.py", line 482, in copyfile
    copyfileordir(src, dest, symlink)
  File "./vendor/virtualenv-12.0.7.py", line 454, in copyfileordir
    shutil.copytree(src, dest, symlink)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 208, in copytree
    raise Error, errors
shutil.Error: [('/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config/config.c', './env/lib/python2.7/config/config.c', "[Errno 1] Operation not permitted: './env/lib/python2.7/config/config.c'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config/config.c.in', './env/lib/python2.7/config/config.c.in', "[Errno 1] Operation not permitted: './env/lib/python2.7/config/config.c.in'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config/install-sh', './env/lib/python2.7/config/install-sh', "[Errno 1] Operation not permitted: './env/lib/python2.7/config/install-sh'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config/libpython2.7.a', './env/lib/python2.7/config/libpython2.7.a', "[Errno 1] Operation not permitted: './env/lib/python2.7/config/libpython2.7.a'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config/libpython2.7.dylib', './env/lib/python2.7/config/libpython2.7.dylib', "[Errno 1] Operation not permitted: './env/lib/python2.7/config/libpython2.7.dylib'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config/Makefile', './env/lib/python2.7/config/Makefile', "[Errno 1] Operation not permitted: './env/lib/python2.7/config/Makefile'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config/makesetup', './env/lib/python2.7/config/makesetup', "[Errno 1] Operation not permitted: './env/lib/python2.7/config/makesetup'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config/python.o', './env/lib/python2.7/config/python.o', "[Errno 1] Operation not permitted: './env/lib/python2.7/config/python.o'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config/Setup', './env/lib/python2.7/config/Setup', "[Errno 1] Operation not permitted: './env/lib/python2.7/config/Setup'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config/Setup.config', './env/lib/python2.7/config/Setup.config', "[Errno 1] Operation not permitted: './env/lib/python2.7/config/Setup.config'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config/Setup.local', './env/lib/python2.7/config/Setup.local', "[Errno 1] Operation not permitted: './env/lib/python2.7/config/Setup.local'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config', './env/lib/python2.7/config', "[Errno 1] Operation not permitted: './env/lib/python2.7/config'")]
make: *** [env] Error 1 
```

**Comment by whit537** [comment]
Hmm ... looks like you're using the system Python. I think folks usually `brew install python` (I use a source-compiled Python), but I think we should aim to work with system Python as well. Lessee here ...

**Comment by whit537** [comment]
"[asked 21 hours ago](http://stackoverflow.com/questions/38491992/virtualenv-with-always-copy-throws-error-operation-not-permitted)"

Do you also go by Cherif? :-P

**Comment by whit537** [comment]
Might have something to do with [system integrity protection](https://support.apple.com/en-us/HT204899)?

**Comment by whit537** [comment]
There's also an easy Python installer for Mac.

**Comment by whit537** [comment]
(I'm thinking of the installers at https://www.python.org/downloads/release/python-2712/.)

**Comment by nashe** [comment]
Personally, I'm using `brew` to get my two up-to-date Python interpreters, since I don't really want to start sudo'ing everything (like in your case). 

I'm sad to read sentences like "System Integrity Protection restricts the root account" :(

**Comment by aandis** [comment]
`brew install python` worked!
Then I hit https://github.com/phusion/passenger/issues/1630 which I fixed with https://github.com/phusion/passenger/issues/1630#issuecomment-147527656.

Off and running again! :)

**Comment by aandis** [comment]
> Do you also go by Cherif? :-P

Haha no. That's just a coincidence I think. I am [aandis](http://stackoverflow.com/users/2643846/aandis) almost everywhere. :)
