### ISSUE TITLE
Fix deploy.sh regression

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#4364]
[Looks](https://github.com/gratipay/gratipay.com/pull/4345#issuecomment-284062013) like #4345 introduced a regression in `deploy.sh`:

```
[gratipay] $ ./deploy.sh 
Already up-to-date.
Traceback (most recent call last):
  File "gratipay/wireup.py", line 11, in <module>
    import aspen
  File "/Users/whit537/personal/gratipay/gratipay.com/env/lib/python2.7/site-packages/aspen/__init__.py", line 65, in <module>
    import pkg_resources
  File "/Users/whit537/personal/gratipay/gratipay.com/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 37, in <module>
    import email.parser
  File "/Users/whit537/personal/gratipay/gratipay.com/gratipay/email.py", line 5, in <module>
    from aspen.simplates.pagination import parse_specline, split_and_escape
  File "/Users/whit537/personal/gratipay/gratipay.com/env/lib/python2.7/site-packages/aspen/simplates/__init__.py", line 15, in <module>
    from .. import log
ImportError: cannot import name log
[gratipay] $
```

**Comment by whit537** [comment]
Ah! https://github.com/gratipay/gratipay.com/blob/796d36e914a44b88e60964416e754c0b473ca163/deploy.sh#L50-L52 is where we're hitting `wireup`.

**Comment by whit537** [comment]
I made a `test.sh` truncated from `deploy.sh`:

```sh
#!/usr/bin/env bash


# Fail on error
set -e


# Be somewhere predictable
cd "$(dirname "$0")"


# Helpers

yesno () {
    proceed=""
    while [ "$proceed" != "y" ]; do
        read -p"$1 (y/n) " proceed
        [ "$proceed" = "n" ] && return 1
    done
    return 0
}

require () {
    if [ ! "$(which "$1")" ]; then
        echo "The '$1' command was not found."
        exit 1
    fi
}


# Check that we have the required tools
require heroku
require git
require curl


# Check that the environment contains all required variables
heroku config -s -a gratipay | ./env/bin/honcho run -e /dev/stdin \
    ./env/bin/python gratipay/wireup.py
```

**Comment by whit537** [comment]
I ran it manually against the commits on #4345. The regression is in https://github.com/gratipay/gratipay.com/commit/b6e89a4696e7451af840c1ac49ca101dcf5526a7.

**Comment by whit537** [comment]
It's because `./gratipay/` is ending up on `sys.path`, and `pkg_resources` tries to import from `email` and it's picking up the `gratipay.email` subpackage. Why is `gratipay/` on `sys.path`?

Ah! It's because `gratipay/wireup.py` is the [script name](), and Python puts `dirname(__file__)` on `sys.path`.

We didn't notice before because there was no `gratipay.email` subpackage to confuse things.
